/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface MediaAttachment {
  'file' : ExternalBlob,
  'mediaType' : MediaType,
}
export type MediaType = { 'video' : null } |
  { 'image' : null };
export interface Post {
  'id' : PostId,
  'media' : Array<MediaAttachment>,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'isLocked' : boolean,
}
export type PostId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMediaToPost' : ActorMethod<[PostId, ExternalBlob, MediaType], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, string, boolean], PostId>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLockedPostContent' : ActorMethod<[PostId], [] | [string]>,
  'getPost' : ActorMethod<[PostId], [] | [Post]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAccess' : ActorMethod<[Principal], undefined>,
  'hasAccess' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'revokeAccess' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePost' : ActorMethod<[PostId, string, string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];